### ISSUE TITLE
Move exceptions and utilities from modulo utils to core

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#115]
The package `modulo_utils` has seen some growth recently on the `breaking` branch by the addition of
1. a parsing helper
2. the definition of the `PredicateVariant`
3. exceptions definitions that are used in modulo components and controllers

Apart from that, it contains the `testutils` as before.

I'm starting to the exceptions should be in `modulo_core` instead. Why? `modulo_core` already defines core exceptions as well and I think the user experience would be improved if all exceptions that components and controllers throw are from the same package. Point 1 and 2 are not the same since the user won't deal with them but for exception handling I think it would be sensible if you only had to include headers from one place, or potentially just one header at all?

@eeberhard @bpapaspyros

**Comment by eeberhard** [comment]
Yes I agree it would be great if core defines core types and exceptions. Linking them in a single `exceptions.hpp` header is not a bad thing either.

I would actually argue that `PredicateVariant` should be in core too as a key defined type, even if it's not user-facing. utils then holds helpers and other stuff which may or may not be user-facing.
