### ISSUE TITLE
Add TF listener in BaseControllerInterface

### ISSUE THREAD

**Issue by bpapaspyros** [aica-technology/modulo#169]
Similarly to our design in `ComponentInterface`, we might imagine that some controllers may want to listen to TFs (i.e., to lookup frames, etc), or even broadcast them (reserved for a follow up issue/discussion).

As such, it's worth copying/adapting some of the functions from `ComponentInterface` to our `BaseControllerInterface`. We would then expose the same design, that is, optionally invoke `add_tf_listener` for controllers that want to use it.

**Comment by bpapaspyros** [comment]
fyi @eeberhard @domire8

**Comment by domire8** [comment]
Absolutely, let's try to duplicate everything related to TF, also broadcaster.
