### ISSUE TITLE
Incorrect parameter logic in declare_signal

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#21]
https://github.com/aica-technology/modulo/blob/7e00bceeaab21473731f2c73ae28175b8b14b8f5/source/modulo_components/include/modulo_components/ComponentInterface.hpp#L918

In my opinion, the logic for the parameter of the signal topic name in `declare_signal` is incorrect. As you can see in the referenced line, the parameter is only set if the parameter already exists and is **empty**. However, imagine the following scenario:
1. Declaration of signal: `declare_signal("name", "default_topic")`. Signal "name" has topic name "default_topic" (the parameter is not empty)
2. Adding the signal later: `add_signal("name", other arguments, "another_topic")`. Now, `add_signal` will internally call `declare_signal` with a different default topic name,
3. As it stands, the topic name parameter value will not be updated, because it is not empty but set to "default_topic"

I believe the expected behaviour should be that `declare_signal` always sets the topic name parameter value if provided. The whole point of declaring a signal was that you don't know the topic name yet and if you then try to add the signal but the topic parameter is not updated, then something is wrong...

**Comment by eeberhard** [comment]
Sorry for the late review, I wanted enough time to think about this one. I'm not sure I fully agree with the issue and think the current behavior is mostly appropriate.

The job of `declare_signal` is to make sure that the topic parameter exists. Calling `declare_signal` on construction and then `add_signal` later in the lifecycle allows for configurable topic names. If we always set the default topic of `add_signal` then it would ignore the user-defined topic set in the parameter.

I think the main difference in opinion is the concept of "default_topic", which to me acts as a fallback to set the topic name _if_ the parameter is not set. But, you are proposing that it behaves more like `override_topic` which sets the topic name _if_ `!override_topic.empty()`. 

To me the current behavior is fine and doesn't need changing, but if you really want to be able to override a signal topic with `add_signal`, then the argument should be renamed to `override_topic` and not `default_topic`.

**Comment by domire8** [comment]
Hmm okay, I see your point. I don't like changing the name to `override_topic` too much because if you only use `add_signal` it should still be the default one. What I would like to see though is a warn message as a compromise:
```
if (NodeT::has_parameter(parameter_name)) {
  if (this->get_parameter(parameter_name)->is_empty()) {
    this->set_parameter_value<std::string>(parameter_name, topic_name);
  } else {
    RCLCPP_WARN(this->get_logger(), "Ignoring default topic");
  }
} else {
  this->add_parameter(
      parameter_name, topic_name, "Signal topic name of " + type + " '" + parsed_signal_name + "'", fixed_topic
  );
}
```
or similar. What do you think? I just want to avoid that people declare topics, then add them with a different default topic and it doesn't have the expected outcome.

**Comment by eeberhard** [comment]
> if you only use add_signal it should still be the default one

Without removing `declare_signal` from `add_signal` internally that would be difficult to really monitor.


- if you `add_signal` in the constructor and the topic parameter is **not** given to the constructor via node options, it should add the signal on the default (fallback) topic
- if you `add_signal` in the constructor and the topic parameter **is** given to the constructor via node options, it should use the parameterized topic. This should not cause a warning in my opinion, because assigning different topic names via parameters is the whole point of dynamically connected nodes
- if you `declare_signal` in the constructor and `add_signal` later, it should just take the topic parameter

**Comment by domire8** [comment]
Yes okay, you convinced me ;) All good from my side then, I will close this issue and the PR with no further action.
