### ISSUE TITLE
Add templated overloads to simplify adding empty parameters

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#24]
See discussion [here](https://github.com/aica-technology/hardware-components/pull/33#discussion_r1177490828).

To facilitate adding empty parameters to components
- [x] Add overloaded `make_shared_parameter(name)` to state representation
- [x] Add overloaded `add_parameter<T>(name)` to modulo component interface

**Comment by domire8** [comment]
As we realized (bad job on my side for not testing properly), the overloaded method creates problems in component packages. For example:
```
add_parameter<int<("name", 0, "description");
```
doesn't work anymore, because the 0 is an implicit constructor for a string (apparently) and then the compiler cannot disambiguate anymore.

We should roll back #25 (how do we do this @eeberhard )

**Comment by eeberhard** [comment]
I think you can revert the commit and set the version to increase the patch number, then just remove the line from the changelog.
