### ISSUE TITLE
Components should also include `on_step_callback`

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/modulo#49]
A key difference between the `Component` and the `LifecycleComponent` is that periodic behaviors (evaluating periodic callbacks and publishing outputs) are executed continuously for basic components but only executed in the active state for lifecycle components.

If a user wants to include some periodic behavior on a basic component, they need to use the `add_periodic_callback` function to register a custom callback to be executed on step. This callback is evaluated on every step.

```cpp
void Component::step() {
  try {
    this->evaluate_periodic_callbacks();
    this->publish_outputs();
    this->publish_predicates();
  } catch ...
  ...
}
```

However, to include periodic behavior on lifecycle components, users have the convenience of overriding the `on_step_callback` function. In the end, the behavior is equivalent to using the `add_periodic_callback` function. 

```cpp
void LifecycleComponent::step() {
  try {
    if (this->get_predicate("is_active")) {
      this->evaluate_periodic_callbacks();
      this->on_step_callback();
      this->publish_outputs();
    }
    this->publish_predicates();
  } catch ...
  ...
}
```

## Suggested change

Define the virtual `on_step_callback()` function in the base `ComponentInterface` class and invoke it in the `Component` step function. That way both types of component have the same interface for default periodic behavior.

```cpp
void Component::step() {
  try {
    this->evaluate_periodic_callbacks();
    this->on_step_callback();
    this->publish_outputs();
    this->publish_predicates();
  } catch ...
  ...
}
```

**Comment by domire8** [comment]
Yeah, I guess that wouldn't hurt :+1:
