### ISSUE TITLE
Support rate or frequency for components

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#52]
See original conversation [here](https://github.com/aica-technology/api/pull/45#discussion_r1324522631)

**Comment by domire8** [comment]
It might be a good time to bring this up again.

I propose to change the syntax to use `rate` instead of `period` and have the state engine compute the period from the rate if rate is provided. This way, we won't have to break the syntax again in the future and we can be backwards compatible with the `period` parameter.

**Comment by domire8** [comment]
```
  rclcpp::Parameter period;
  for (auto& parameter : parameters) {
    if (parameter.get_name() == "period" && period.get_type() == rclcpp::ParameterType::PARAMETER_NOT_SET) {
      period = parameter;
    } else if (parameter.get_name() == "rate") {
      if (parameter.get_type() != rclcpp::ParameterType::PARAMETER_INTEGER) {
        RCLCPP_ERROR(
            this->get_logger(),
            "Could not load node %s: Invalid parameter value for parameter rate: expected [int] got [%s]",
            node_name.c_str(), parameter.get_type_name().c_str());
        return false;
      }
      period = rclcpp::Parameter("period", 1.0 / parameter.as_int());
    } else {
      request->parameters.push_back(parameter.to_parameter_msg());
    }
  }
  if (period.get_type() != rclcpp::ParameterType::PARAMETER_NOT_SET) {
    request->parameters.push_back(period.to_parameter_msg());
  }
```
something like that in the DSE ComponentManagerInterface

@eeberhard

**Comment by eeberhard** [comment]
> This way, we won't have to break the syntax again in the future

Discussions around YAML application syntax belong in the aica-technology/api repository, but I will say that the application schema is wholly unaffected by the naming of rate vs period. The syntax simply provides a place for component parameter values to be defined, regardless of parameter names.

I still agree that `rate` might be a more intuitive parameter for components, but that is something that foremost affects modulo and any component implementations. For one, the closest thing to a schema for this case are the modulo `component_descriptions` which specify the built-in interfaces, including the `period` parameter. 

In my opinion, modulo would still have to be the main driver of this change. Perhaps it could be done in a backwards compatible way by declaring both parameters but including only `rate` in the component description.

**Comment by domire8** [comment]
Breaking the syntax was indeed poor choice of words.

I just want to make sure that if we start writing application with the new unified yaml syntax, we don't have to go back to them a few weeks later just because we deprecated the `period` parameter, even though those two things are not directly related. It's just to reduce maintenance and also to be more consistent and clearer in the docs.

So as you propose, I would like to add the `rate` parameter in addition to the `period` in a 3.2.0 version of modulo for backwards compatibility and then at some point remove it (when we also remove backwards compatibility in the DSE).

Does this sound reasonable to you?

**Comment by eeberhard** [comment]
I think that's the right approach yes 👍 similar to something you already suggested for a different repo, there is a way that a component could back-fill the period parameter from a rate parameter (if it exists), meaning existing components that access the period parameter for calculations will not break
