### ISSUE TITLE
Add mutex around step callback

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/modulo#67]
After discoveries in https://github.com/aica-technology/stag/issues/7, there is a chance that the DSE state event handler unloads a component in one thread while the component step function is being handled in another thread. This race condition can cause memory issues and crashes.

Adding a mutex around the component step callback and the destructor could safeguard this race condition in a general way.

**Comment by domire8** [comment]
Reopening this, since we need to revert the revert commit once we are ready for a breaking 5.0.0 version
