### ISSUE TITLE
Python subscriptions are not type safe

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#71]
https://github.com/aica-technology/modulo/blob/59b4b6effd2ab5f7e24b1a8c4e359442871538b9/source/modulo_components/modulo_components/component_interface.py#L429

@yrh012 found out that if you add an input of a certain state representation type (so `EncodedType`), and connect it to a topic that is also publishing an encoded state but of different state representation type, the attribute will be overridden with the received message. If we want to be consistent with C++, we should probably attempt a cast on the received message such that the attribute type of the subscribing component doesn't change.

Opinions? @eeberhard @bpapaspyros

**Comment by eeberhard** [comment]
Classic Python. It's true that from the users perspective, the type of the class attribute should not change if a valid input is received and decoded. For the best way to implement it, I am not sure, but it seems like a reasonable backlog issue to address whenever a contributor has some time.
