### ISSUE TITLE
Modulo controller interface

### ISSUE THREAD

**Issue by domire8** [aica-technology/modulo#82]
Add a `modulo_controller_interface` package to make the base class for modulo controller public.

(potentially an Epic)

**Comment by domire8** [comment]
I think something that has to be considered here is if we want to make the `RobotControllerInterface` available publicly as well. I think it should be, since it just adds helpers for controllers that act on `standard` robot arms with revolute joints in series.

@eeberhard @bpapaspyros

**Comment by bpapaspyros** [comment]
I agree it should be public. I think it's nice to set the direction for these developments publicly and adding some basic helpers isn't a bad idea either.
